import os
import pytest
from app.core.config import settings
from app.forms.normalizer import FormNormalizer
from app.etl.transformer import DataTransformer
from app.etl.validator import DataValidator
from app.etl.enricher import DataEnricher
from app.etl.pipeline import ETLPipeline
from app.database.database import SessionLocal, init_db

@pytest.fixture(scope="module", autouse=True)
def setup_db_and_paths():
    """Initializes local db and makes sure folders exist before testing."""
    init_db()
    for folder in ["input", "salesforce_exports", "staging", "output", "errors", "archive"]:
        os.makedirs(os.path.join(settings.DATA_DIR, folder), exist_ok=True)
    yield

def test_form_normalization():
    # India form raw headers
    india_raw = [
        {"Name": "John Doe", "Email": "john@example.com", "Product": "PRD_SLR_01", "Budget_Code": "BDG_IND_2026", "Budget": "10000", "Checklist": "CHK_STD_01", "CRM_ID": "camp_india_01"}
    ]
    norm_res = FormNormalizer.normalize(india_raw, "india_launch")
    assert norm_res["source_name"] == "india_launch"
    assert norm_res["country"] == "India"
    assert norm_res["records"][0]["customer_name"] == "John Doe"
    assert norm_res["records"][0]["email"] == "john@example.com"
    assert norm_res["records"][0]["product_code"] == "PRD_SLR_01"
    assert norm_res["records"][0]["budget_code"] == "BDG_IND_2026"
    assert norm_res["records"][0]["budget"] == "10000"
    
    # UAE form raw headers
    uae_raw = [
        {"Full_Name": "Mohammed Ali", "Email_Address": "mohammed@example.ae", "Product_Code": "PRD_WND_02", "Budget_Code": "BDG_UAE_2026", "Allocated_Budget": "15000", "CRM_ID": "camp_uae_01"}
    ]
    norm_res_uae = FormNormalizer.normalize(uae_raw, "uae_launch")
    assert norm_res_uae["source_name"] == "uae_launch"
    assert norm_res_uae["country"] == "UAE"
    assert norm_res_uae["records"][0]["customer_name"] == "Mohammed Ali"
    assert norm_res_uae["records"][0]["email"] == "mohammed@example.ae"
    assert norm_res_uae["records"][0]["product_code"] == "PRD_WND_02"
    assert norm_res_uae["records"][0]["budget_code"] == "BDG_UAE_2026"
    assert norm_res_uae["records"][0]["budget"] == "15000"

def test_data_transformation():
    raw = [
        {"customer_name": "john doe", "email": "JOHN@EXAMPLE.COM", "event": "product launch", "country": " India "}
    ]
    transformer = DataTransformer()
    transformed = transformer.transform(raw)
    assert transformed[0]["customer_name"] == "John Doe"
    assert transformed[0]["email"] == "john@example.com"
    assert transformed[0]["event"] == "PRODUCT LAUNCH"
    assert transformed[0]["country"] == "India"

def test_data_enrichment():
    # We must have products master data generated by our mock data generator in the export folder
    raw = [
        {"product_code": "PRD_SLR_01", "budget_code": "BDG_IND_2026", "checklist_code": "CHK_STD_01"}
    ]
    enricher = DataEnricher()
    enriched = enricher.enrich(raw)
    
    # Verify lookups resolved the Salesforce ID correctly
    assert enriched[0]["product_sfdc_id"] == "prod_001"
    assert enriched[0]["budget_sfdc_id"] == "bud_001"
    assert enriched[0]["checklist_sfdc_id"] == "chk_001"
    assert enriched[0]["_lookup_failed"] is False

def test_data_validation():
    # 1. Valid record
    valid_recs = [
        {"customer_name": "John Doe", "email": "john@example.com", "product_code": "PRD_SLR_01", "budget": "5000", "event": "Launch"}
    ]
    validator = DataValidator()
    val_ok, val_fail = validator.validate(valid_recs, "india_launch")
    assert len(val_ok) == 1
    assert len(val_fail) == 0

    # 2. Invalid record (missing required name, invalid email, negative budget)
    invalid_recs = [
        {"customer_name": "", "email": "invalid-email", "product_code": "PRD_SLR_01", "budget": "-100", "event": "Launch"}
    ]
    val_ok, val_fail = validator.validate(invalid_recs, "india_launch")
    assert len(val_ok) == 0
    assert len(val_fail) == 1
    errs = val_fail[0]["_validation_errors"]
    rules = [e["rule"] for e in errs]
    assert "required" in rules
    assert "email_format" in rules
    assert "business_rule_>=" in rules

    # 3. Duplicate detection within the same batch
    dup_recs = [
        {"customer_name": "John", "email": "john@example.com", "product_code": "PRD_SLR_01", "event": "Launch"},
        {"customer_name": "John", "email": "john@example.com", "product_code": "PRD_SLR_01", "event": "Launch"}
    ]
    val_ok, val_fail = validator.validate(dup_recs, "india_launch")
    assert len(val_ok) == 1
    assert len(val_fail) == 1
    assert val_fail[0]["_is_duplicate"] is True

def test_pipeline_dry_run():
    # Run pipeline on our mock India form
    filepath = os.path.join(settings.SAMPLE_DATA_DIR, "sample_form_india.xlsx")
    
    db = SessionLocal()
    pipeline = ETLPipeline(db)
    try:
        summary = pipeline.run(filepath, "india_launch", dry_run=True)
        assert summary["status"] in ["SUCCESS", "PARTIAL_SUCCESS"]
        assert summary["received"] == 5
        assert summary["successful"] == 2 # Row 1 & Row 5 succeed (Row 5 fails in live loading, but succeeds in dry-run)
        # 3 fails (Row 2 lookup failure, Row 3 validation failure, Row 4 duplicate validation failure)
        assert summary["failed"] == 3
        assert summary["skipped"] == 1
    finally:
        db.close()
